app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');


Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

Route::resource('/','WelcomeController');
// Route::resource('admin','AdminController');
// Route::resource('users','UsersController');

Route::controller('page','PagesController');




// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){

		Route::resource('users','UsersController');
		Route::resource('admin','AdminController');
		Route::resource('admin.staffs','StaffsController');
		Route::resource('departments','DepartmentsController');
		Route::resource('staffs','StaffsController');
		Route::resource('departments.staffs','StaffsController');
		Route::resource('courses','CoursesController');
		Route::resource('departments.courses','CoursesController');
		Route::resource('students','StudentsController');
		Route::resource('students.complete','PreController',array('only'=>array('index','show','store')));
		Route::resource('courses.students','StudentsController');
		Route::resource('search','SearchController',array('only' => array('index','show','store')));
		Route::resource('search.persons','SearchController');
		Route::resource('Documents', 'DocumentsController');
		Route::resource('data_entry', 'DataEntriesController');
		Route::resource('certificates', 'CertificatesController');
		Route::resource('work', 'EmploymentsController');


});
// Route::get('test',function(){
// 	// var_dump(User::select(DB::raw('select * from users')));
	
// });
// Event::listen('illuminate.query',function($query){
// 	// dd($query);
// 	echo '<pre style="margin:200px 80px">';
// 	print_r($query);
// 	echo '</pre>';
// });
// Route::get('/company-profile', function() {
//     return View::make('companyprofile');
// });

app/views/admin/index.blade.php
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="icons_zone">
		
			<p>
				<a href="departments" class="imgthumb">
					<i class="fa fa-university"></i> 
				</a>
				<a href="departments">Departments</a>
			</p>
			<p>
				<a href="courses" class="imgthumb">
					<i class="fa fa-book"></i>
				</a>
				<a href="courses">Courses</a>
			</p>
			<p>
				<a href="staffs" class="imgthumb">
					<i class="fa fa-pencil"></i>
				</a>
				<a href="staffs">Staff</a>
			</p>
			<p>
				<a href="students" class="imgthumb">
					<i class="fa fa-child"></i>
				</a>
				<a href="students">Students</a>
			</p>
		</div><!-- content conent -->	
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/search.blade.php
<?php 	#page specifig procssing
// var_dump($data);

// die()	;
 ?>
@include('templates/top-admin')
@section('content')
	<div class="cc">
	<section>
		<?php if (!empty($data)): ?>
			<div class="stats">	
				<a href="#">fetch results</a>
			</div>	
			<hr>
			<ul class="search-results">
				<?php foreach ($data as $key => $value): ?>
				<?php if ($key == 'person' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
							<?php if (isset($value1['students'])): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<?php $perstype = (isset($value1['pers_type']) && $value1['pers_type'] == 'Staff')? 'staffs' : 'students'; ?>

							<a href="<?php echo $perstype.'/'.$value1['id'] ?>"><?php echo $value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']; ?></a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>
						<?php endif ?>
						<?php if (	isset($value1['staffs'])): ?>

						<li class="result">
							<div class="search-detail">
							<strong>
								<?php $perstype = (isset($value1['pers_type']) && $value1['pers_type'] == 'Staff')? 'staffs' : 'students'; ?>

	<a href="<?php echo $perstype.'/'.$value1['staffs']['staff_id'] ?>"><?php echo $value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']; ?></a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>								
						<?php endif ?>
						
					<?php endforeach ?>
				<?php endif ?>
				<?php if ($key == 'department' ): ?>
				<?php foreach ($value as $ind => $depart): ?>
					<li class="result">
						<div class="search-detail">
						<strong>
							<a href="{{route('departments.index')}}">{{e(ucwords($depart['name']))}}</a>
						</strong>
						<p>
							<span>Result Type : </span> <strong>{{e($key)}}</strong> |
							<span>Person in charge : </span> <strong>{{e($depart['personName'])}}
						</p>
						</div>
						<hr>
					</li>						
				<?php endforeach ?>
				
				<?php endif ?>
				<?php if ($key == 'contact' ): ?>
					<?php foreach ($value as $ind => $cont): ?>
					<?php $perstype = ($cont['persons']['pers_type'] == 'Staff')? 'staffs' : 'students'; ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="<?php echo 'search/persons?pers='.$cont['persons']['pers_type'].'&key='.$cont['persons']['id']; ?>">
								<?php echo ucwords($cont['persons']['pers_fname'].' '.$cont['persons']['pers_mname'].' '.$cont['persons']['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Contact Type : </span> <strong>{{$cont['Cont_ContactType']}}</strong> |
								<span>Contact Info : </span> <strong>{{$cont['Cont_Contact']}}</strong> 
							</p>
							<p>
								<span>Person Type : </span> <strong>{{$cont['persons']['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$cont['persons']['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$cont['persons']['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>						
					<?php endforeach ?>
					
				<?php endif ?>
				<?php if ($key == 'course' ): ?>
				<?php foreach ($value as $key => $course): ?>
					<li class="result">
						<div class="search-detail">
						<strong>
							<a href="{{route('departments.courses.show',[$course['depart_id'],$course['id']])}}">{{e(ucwords($course['name']))}}</a>
						</strong>
						<p>
							<span>Search Type : </span> <strong>Course</strong> |
						</p>
						</div>
						<hr>
					</li>					
				<?php endforeach ?>
					
				<?php endif ?>					
				<?php endforeach; ?>				
			</ul>
			<div class="stats">	
					<a href="#">fetch results</a>
			</div>	
			<?php else: ?>
				<h3>Sorry there were no results</h3>
		<?php endif ?>

	</section>
	</div>
@stop
@include('templates/bottom-admin')