app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');


Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

Route::resource('/','WelcomeController');
// Route::resource('admin','AdminController');
// Route::resource('users','UsersController');

Route::controller('page','PagesController');




// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){

		Route::resource('users','UsersController');
		Route::resource('admin','AdminController');
		Route::resource('admin.staffs','StaffsController');
		Route::resource('departments','DepartmentsController');
		Route::resource('staffs','StaffsController');
		Route::resource('departments.staffs','StaffsController');
		Route::resource('courses','CoursesController');
		Route::resource('departments.courses','CoursesController');
		Route::resource('students','StudentsController');
		Route::resource('students.complete','PreController',array('only'=>array('index','show','store')));
		Route::resource('courses.students','StudentsController');
		Route::resource('search','SearchController',array('only' => array('index','show','store')));
		Route::resource('search.persons','SearchController');
		Route::resource('Documents', 'DocumentsController');
		Route::resource('data_entry', 'DataEntriesController');
		Route::resource('certificates', 'CertificatesController');
		Route::resource('work', 'EmploymentsController');


});
// Route::get('test',function(){
// 	// var_dump(User::select(DB::raw('select * from users')));
	
// });
// Event::listen('illuminate.query',function($query){
// 	// dd($query);
// 	echo '<pre style="margin:200px 80px">';
// 	print_r($query);
// 	echo '</pre>';
// });
// Route::get('/company-profile', function() {
//     return View::make('companyprofile');
// });

app/views/__partials/doc.blade.php
<?php
// session targeting
// title targeting
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    <!-- <meta http-equiv="refresh" content="2" /> -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo '$title';  ?></title>
        <meta name="description" content="information system">
        <meta name="author" content="Mamadou Jallow <sulsiralumo@gmail.com>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->    

app/views/__partials/errors.blade.php
@if ($errors->any())
<div class="alert alert-error">
	 <button type="button" class="close" data-dismiss="alert">&times;</button>
	<h2>Errors</h2>
		<ul>
			{{ implode('',$errors->all('<li  class="bg-danger text-danger">:message</li>')) }}
		</ul>	
</div>

@endif

app/views/__partials/menu.blade.php
@if(!empty($menu))
		<div class="fixheda">
			<div class="userheda fixheda_style">
				<div class="hedacont">
					<ul class="navigation">
					@foreach ($menu as $key => $value) 
						@if($value['visible'] == 1)
							@if($value['type'] == 'single')
								<li>{{HTML::link($value['url'],$value['name'],['class'=>'link'])}}</li>
							@endif
						@endif
					@endforeach
				</ul>	            
	            <div class="navbar" id="user_options">
					<ul class="nav pull-right">
					@foreach ($menu as $key => $value) 
						@if($value['visible'] == 1)
							@if($value['type'] == 'drop')
								<li class="dropdown">
									{{HTML::link($value['url'],$value['name'],['class'=>'dropdown-toggle usrname fix', 'data-toggle'=>"dropdown"])}}
										<ul class="dropdown-menu">
											@foreach($value['menu'] as $ke => $valu)
										<li>
											{{HTML::link($valu['url'],$valu['name'])}}<b class="caret"></b> 		
										</li>									
											@endforeach
									</ul>
								</li>
							@endif
						@endif
					@endforeach
					</ul>       								                 		            	
	            </div>
				</div>

		  		<div class="acctheda  fixheda_style">
					<div class="navbar">
					 	<div class="navbar-inner">
							<div class="hedacont">	
							    <a class="active brand blr" href="#" id="menu" title="Management Development Institution"><i class="fa fa-bars"></i></i>MDI</a>
							    <ul class="nav">
							      <li><a href="{{route('courses.students.create')}}">Add Student</a></li>
							      <li><a href="{{route('departments.staffs.create')}}">Add Staff</a></li>
							      <li><a href="{{route('departments.create')}}">Add Department</a></li>
							      <li><a href="{{route('departments.courses.create')}}">Add Course</a></li>
							      <li class="blr">
							      	<a href="#" id="checker">Check Student</a>
							      </li>
							    </ul>
							    	<div class="popover fade bottom in" id="studentChecker">
							      		<div class="arrow"></div>
							      		<h3 class="popover-title">Checking For A Student</h3>
							      		<div class="popover-content">
											<div class="tabbable"> <!-- Only required for left/right tabs -->
											  <ul class="nav nav-tabs">
											    <li class="active"><a href="#tab1" data-toggle="tab">Student ID</a></li>
											    <li><a href="#tab2" data-toggle="tab">Student Details</a></li>
											  </ul>
											  <hr>
											  <div class="tab-content">
											    <div class="tab-pane active" id="tab1">
									      			{{Form::open(array('action'=>'PagesController@postFetch','method'=>'POST'))}}
									      				<div class="input-prepend">
														  <span class="add-on">StudentID</span>
														  {{Form::text('studentID',null,['class'=>"span6",'placeholder'=>"Student ID",'required'=>1])}}
														</div>
													<div class="form-actions">
													  <button type="submit" class="btn btn-primary">Get Student</button>
													  <button type="button" class="btn">Cancel</button>
													</div>
									      			{{Form::close()}}
											    </div>
											    <div class="tab-pane" id="tab2">
									      			{{Form::open(array('action'=>'PagesController@postFind','method'=>'POST'))}}
									      				<div class="input-prepend">
									      				<label>Student Name :</label>
														  <span class="add-on">First</span>
														  {{Form::text('pers_fname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
														 <span class="add-on">Middle</span>{{Form::text('pers_mname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
														<span class="add-on">last</span>{{Form::text('pers_lname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
														</div>
														<hr>
									      				<label>Student Details :</label>
									      				<div class="input-prepend">
														  <span class="add-on">Birthday</span>
										{{Form::date('pers_DOB',['class'=>"span2", 'placeholder'=>"Student birthday",'required'=>1])}}
														</div>
									      				<div class="input-prepend">
														  <span class="add-on">Course</span>
															<select name="course_id" class="input-xlarge">
																<?php $course = Course::all();  ?>
																<?php foreach ($course as $key => $value): ?>
																	<option value="{{$value['id']}}">{{$value['name']}}</option>
																<?php endforeach ?>
															</select>
														</div>
														<div class="form-actions">
														  <button type="submit" class="btn btn-primary">Get Student</button>
														  <button type="button" class="btn">Cancel</button>
														</div>
									      			{{Form::close()}}
											    </div>
											  </div>
											</div>
							      		</div>
							      	</div>
							    {{Form::open(array('route'=>'search.store','method'=>'get'))}}
									<div class="input-append">
										{{ Form::text('q',null,['class'=>'span5','placeholder'=>"seach here",'id'=>"appendedInputButtons",'required'=>1]) }}
										{{ Form::hidden('x',1) }}	
									  	<button class="btn" type="submit" name="type" value="natural">Search</button>
									</div>
								{{Form::close()}}
							</div>

						<div class="sidebar">
							<ul>
					            <li><a href="{{route('admin.index')}}" class="ui-link"><i class="fa fa-chevron-circle-left"></i>MDI info</a></li>
					            <li><a href="{{route('departments.create')}}" class="ui-link"><i class="fa fa-plus"></i>Departments</a></li>
								<li><a href="{{route('departments.staffs.create')}}" class="ui-link"><i class="fa fa-plus"></i>Staff</a></li>
					            <li><a href="{{route('departments.courses.create')}}" class="ui-link"><i class="fa fa-plus"></i>Courses</a></li>
					            <li><a href="{{route('courses.students.create')}}" class="ui-link"><i class="fa fa-plus"></i>Students</a></li>
					            <li><a href="#" class="ui-link"><i class="fa fa-cog"></i> Settings</a></li>
				            </ul>
						</div>
					</div>						  			
		  		</div>	
			</div>
			</div>	
		</div>
@endif

app/views/__partials/modal-add-user.blade.php
<!-- Modal -->

<div id="add-user" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create A user</h3>
  </div>
	  {{Form::open(array('route'=>'users.store'))}}
		  <div class="modal-body">
				<strong>
						Fullname
				</strong>														
				<div class="input-feild">
					<input id="fullname" type="text" placeholder="Enter your Fullname" name="username" class="span5" required>
					<span class="help-block">Enter your fullname </span>
				</div>
				<strong>
						Email
				</strong>														
				<div class="input-feild">
					<input id="email" type="email" placeholder="email address" name="email" class="span5"  data-validation="email" required>
				</div>
				<!-- <hr> -->
				<strong>
						Password
				</strong>														
				<div class="input-feild">
					<input id="password" type="password" placeholder="enter new password" name="password" class="span5" data-validation="strength" 
						data-validation-strength="2" required>
					<span class="help-block">minimum is 6 characters</span>									
				</div>
				<!-- <hr> -->
				<strong>
						Mobile Phone
				</strong>														
				<div class="input-feild">
					<input type="text" name="mobile" id="mobile" placeholder="fullname"  class="span5" data-validation="number">
					<span class="help-block">example 7052217</span>

				</div>

				<hr>
				<strong>
						Previleges
				</strong>														
				<div class="input-feild">
				<select name="Previleges" id="accountPriv" class="span5">
					<option value="veda">view edit add and delete</option>
					<option value="ve">view and edit</option>
					<option value="v">view</option>
				</select>	
					<span class="help-block">Access on how the user manipulate assignment data</span>
				</div>	
		  </div>
			<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" name="createUser">Save changes</button>
			</div><!-- end of modal footer -->		
	 {{Form::close()}}
</div>